### PR TITLE
Added working Gem Guideline link

### PR DESCRIPTION
**Pull request by priyamm**
## Items Addressed
Added the working Gem Guideline link in contributing.md

## Author Checklist
- [x] Update documentation (if necessary)
- [x] Update version in `version.rb` following [versioning guidelines](https://github.com/LaunchPadLab/opex-public/blob/master/gists/gem-guidelines.md#pull-requests-and-deployments)

### CODE REVIEW

**Comment by priyamm** [comment]
#106

**Comment by priyamm** [comment]
@chawes13 is there anything else needs to be added, can you review and merge it. I suppose documentation would not need a version bump.

**Comment by chawes13** [comment]
@priyamm I would consider this a [patch](https://semver.org/) update.  Please make the update accordingly

**Review by chawes13 — CHANGES_REQUESTED** [review]
Thanks for finding the other reference for this link! However, the Gem guidelines link that you changed does not need to the anchor hash.

There is another location where this link is used (`./github/PULL_REQUEST_TEMPLATE.md`), which should have the url and anchor hash specifically pointing to the Pull Requests and Deployments section.

Please also include a version bump.

**Comment by priyamm** [comment]
@chawes13 yeah I also thought the same about anchor tags

**Comment by priyamm** [comment]
@chawes13 have made the final changes.

**Review by chawes13 — APPROVED** [review]
🎉

**Pull request merged**
