### PR TITLE
Address dependency security vulnerabilities

### PR DESCRIPTION
**Pull request by AngelMDev**
## Items Addressed
Tried to update dependencies to the latest version that had a patch for the vulnerability while minimizing potential breaking changes. With that said the only larger version increase was for `rake` from `10.5` to `12.3.3`. Here are the documented compatibility changes from the [rake gem changelog](https://github.com/ruby/rake/blob/master/History.rdoc):
```
* Bump `required_ruby_version` to Ruby 2.0.0. Rake has already removed support for Ruby 1.9.x.
* Removed constant named `RAKEVERSION` 
* Removed Rake::AltSystem 
* Removed Rake::RubyForgePublisher 
* Removed Rake::TaskManager#last_comment. Use last_description. 
* Removed Rake::TaskLib#paste 
* Removed Top-level SshDirPublisher, SshFreshDirPublisher, SshFilePublisher and CompositePublisher from lib/rake/contrib/publisher.rb 
* Removed “rake/runtest.rb” 
* Removed arguments on clear #157 by Jesse Bowes
* Removed `rake/contrib` packages. These are extracted to `rake-contrib` gem
* Removed deprecated method named `last_comment`.
```
I doubt any of these affect us but thought it would be good to have them here just in case.

## Author Checklist
- [x] Update version in `version.rb` following [versioning guidelines](https://github.com/LaunchPadLab/opex-public/blob/master/gists/gem-guidelines.md#pull-requests-and-deployments)

### CODE REVIEW

**Comment by AngelMDev** [comment]
Also, don't understand why the build is failing after that last commit, maybe a configuration error?

**Comment by chawes13** [comment]
@AngelMDev You'll have to update the version in `gemfile.lock` as well (manually)

**Review by chawes13 — COMMENTED** [review]
Looks good, just need the builds passing!

**Review by chawes13 — APPROVED** [review]
🎉

**Pull request merged**
